### PR TITLE
Fix #79 - Use plexus to support classpath resources

### LINKED ISSUE #79: Support for classpath resources for definitions and ignore lists
I am using a Maven aggregator pom to set up common plugins that are used across many projects.
I use this to set coding standards throughout these projects (PMD, Checkstyle, Spotless, etc) and one of the checks I run is for out of date dependencies, using this plugin 😄 

This 'parent pom' is an aggregator project and as such cannot include files for use in downstream projects.
When the checks are run I would like to have a constant set of ignores and definitions across all of the projects which use this parent.

Currently this plugin gives me two options:
- HTTP hosted files - As all of my code is in a private organization having a HTTP hosted file is not possible as the file can contain internal sensitive details (e.g. library names)
- Absolute/relative file references - This is awkward as I would have to either copy a file into every repo or have the file present on my build system which can be fragile

When using other plugins like PMD you can include a dependency in the plugin definition which allows usage of a classpath file:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-pmd-plugin</artifactId>
    <configuration>
        <rulesets>
            <ruleset>pmd_rules.xml</ruleset>
        </rulesets>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>uk.me.thega</groupId>
            <artifactId>all-of-my-plugin-config-files</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</plugin>
```

This allows all downstream projects to have the same configuration applied without having to copy and paste the configuration around (or web host it).

Is this behavior possible already and I am missing something or do we think it is valuable to add?

I already have an initial version of support [here](https://github.com/pwhittlesea/oga-maven-plugin/commit/4a61d877ed10e18258d4957bdd519fd5a524b85b) and I am happy to write some tests and create a PR.

I think there is an initial step where support could be added for the file properties, but ultimately we could switch the configuration to remove the different concepts for 'file' and 'url' and do something similar to PMD (see above) where you can just add paths. But that would be a bigger, breaking change.

### PR DESCRIPTION
**Pull request by pwhittlesea**
Fixes #79 

The code here is inspired by the PMD maven plugin
https://github.com/apache/maven-pmd-plugin/blob/4afad98d229a6764d2ebdd246c037d1645c7cbb9/src/main/java/org/apache/maven/plugins/pmd/PmdReport.java#L394

The aim is to support classpath configuration when using this plugin in parent aggregator projects where config is in a plugin dependency.

### CODE REVIEW

**Comment by pwhittlesea** [comment]
@jonathanlermitage The tests are passing locally for me but I'm not sure why they are failing here. Is there a way to pull the Maven `log.txt` files to see what happened?

**Comment by pwhittlesea** [comment]
> @jonathanlermitage The tests are passing locally for me but I'm not sure why they are failing here. Is there a way to pull the Maven `log.txt` files to see what happened?

Figured it out 😄

**Comment by jonathanlermitage** [comment]
Thanks!

**Comment by jonathanlermitage** [comment]
Hum, Maven makes some resistance, again 😅 I will try to publish the new 1.9.0 release asap. 
I used to deploy by running:  
```
mvn clean release:prepare
mvn release:perform -P ossrh
```
(my ossrh maven profile is configured with my Sonatype creds, and my gpg passphrase)  
but the second command fails saying  
```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project oga-maven-plugin: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::url parameter -> [Help 1]
```
It will simply take some time...

**Comment by pwhittlesea** [comment]
Ooh that sounds rough @jonathanlermitage. I'm going to guess that because it's login related there is not much I can do to help, but if there is let me know!

Good luck!

**Comment by jonathanlermitage** [comment]
No problem, the Sonatype support helped me a lot. I just published the 1.9.1 release (strictly identical to 1.9.0) with success. It should be available in Central very soon. 🥳

**Pull request merged**
